[toolchain]
anchor_version = "1.0.2"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vsol = "2SgyYptw5rMFsTKHiP95c5K3porxFrcsz6fb4mBfDa1v"

[programs.devnet]
vsol = "2SgyYptw5rMFsTKHiP95c5K3porxFrcsz6fb4mBfDa1v"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
commitment = "confirmed"

[scripts]
test = "cargo test --workspace --all-targets"
