import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const positions = sqliteTable(
  "positions",
  {
    id: text("id").primaryKey(),
    userEmail: text("user_email").notNull(),
    walletAddress: text("wallet_address").notNull(),
    quoteId: text("quote_id").notNull(),
    maker: text("maker").notNull(),
    symbol: text("symbol").notNull(),
    direction: text("direction", { enum: ["up", "down"] }).notNull(),
    amount: real("amount").notNull(),
    premium: real("premium").notNull(),
    strike: real("strike").notNull(),
    capPrice: real("cap_price").notNull(),
    expiryDays: integer("expiry_days").notNull(),
    expiryCode: text("expiry_code").notNull().default("7D"),
    optionExpiryAt: integer("option_expiry_at", { mode: "timestamp_ms" }).notNull().default(sql`0`),
    observationWindowSeconds: integer("observation_window_seconds").notNull().default(900),
    tradeLockSeconds: integer("trade_lock_seconds").notNull().default(300),
    status: text("status", { enum: ["preview_confirmed", "settled"] }).notNull(),
    transactionSignature: text("transaction_signature"),
    simulationId: text("simulation_id"),
    simulationStatus: text("simulation_status", { enum: ["passed", "failed"] }),
    simulationSlot: integer("simulation_slot"),
    simulationUnitsConsumed: integer("simulation_units_consumed"),
    simulationLogsHash: text("simulation_logs_hash"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [
    index("positions_user_created_idx").on(table.userEmail, table.createdAt),
    index("positions_wallet_idx").on(table.walletAddress),
    uniqueIndex("positions_quote_unique_idx").on(table.quoteId),
  ],
);

export const transactionSimulations = sqliteTable(
  "transaction_simulations",
  {
    id: text("id").primaryKey(),
    userEmail: text("user_email").notNull(),
    walletAddress: text("wallet_address").notNull(),
    quoteId: text("quote_id").notNull(),
    positionAddress: text("position_address").notNull(),
    transactionHash: text("transaction_hash").notNull(),
    status: text("status", { enum: ["passed", "failed"] }).notNull(),
    slot: integer("slot"),
    unitsConsumed: integer("units_consumed"),
    logsJson: text("logs_json").notNull(),
    logsHash: text("logs_hash").notNull(),
    errorJson: text("error_json"),
    transactionSignature: text("transaction_signature"),
    submissionStatus: text("submission_status", { enum: ["not_sent", "confirmed", "failed"] }).notNull(),
    submissionError: text("submission_error"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    confirmedAt: integer("confirmed_at", { mode: "timestamp_ms" }),
  },
  (table) => [
    index("transaction_simulations_user_created_idx").on(table.userEmail, table.createdAt),
    index("transaction_simulations_quote_idx").on(table.quoteId),
    uniqueIndex("transaction_simulations_hash_unique_idx").on(table.transactionHash),
  ],
);

export const rfqQuotes = sqliteTable(
  "rfq_quotes",
  {
    id: text("id").primaryKey(),
    requestId: text("request_id").notNull(),
    maker: text("maker").notNull(),
    symbol: text("symbol").notNull(),
    direction: text("direction", { enum: ["up", "down"] }).notNull(),
    amount: real("amount").notNull(),
    premium: real("premium").notNull(),
    maxPayout: real("max_payout").notNull(),
    strike: real("strike").notNull(),
    capPrice: real("cap_price").notNull(),
    breakeven: real("breakeven").notNull(),
    pricingVolatility: real("implied_volatility").notNull(),
    volatilitySource: text("volatility_source").notNull().default("legacy"),
    effectiveLeverage: real("effective_leverage").notNull(),
    latencyMs: integer("latency_ms").notNull(),
    badge: text("badge").notNull(),
    expiryDays: integer("expiry_days").notNull(),
    expiryCode: text("expiry_code").notNull().default("7D"),
    optionExpiryAt: integer("option_expiry_at", { mode: "timestamp_ms" }).notNull().default(sql`0`),
    observationWindowSeconds: integer("observation_window_seconds").notNull().default(900),
    tradeLockSeconds: integer("trade_lock_seconds").notNull().default(300),
    payoff: integer("payoff").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    consumedAt: integer("consumed_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [index("rfq_quotes_expiry_idx").on(table.expiresAt)],
);
