import { sql } from "drizzle-orm";
import {
  boolean,
  doublePrecision,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const positions = pgTable(
  "positions",
  {
    id: text("id").primaryKey(),
    userEmail: text("user_email").notNull(),
    walletAddress: text("wallet_address").notNull(),
    quoteId: text("quote_id").notNull(),
    marketAddress: text("market_address").notNull().default(""),
    oracleAddress: text("oracle_address").notNull().default(""),
    maker: text("maker").notNull(),
    symbol: text("symbol").notNull(),
    direction: text("direction", { enum: ["up", "down"] }).notNull(),
    amount: doublePrecision("amount").notNull(),
    premium: doublePrecision("premium").notNull(),
    strike: doublePrecision("strike").notNull(),
    capPrice: doublePrecision("cap_price").notNull(),
    expiryDays: integer("expiry_days").notNull(),
    expiryCode: text("expiry_code").notNull().default("7D"),
    optionExpiryAt: timestamp("option_expiry_at", { mode: "date", withTimezone: true }).notNull().default(sql`to_timestamp(0)`),
    observationWindowSeconds: integer("observation_window_seconds").notNull().default(900),
    tradeLockSeconds: integer("trade_lock_seconds").notNull().default(300),
    status: text("status", { enum: ["preview_confirmed", "settled"] }).notNull(),
    transactionSignature: text("transaction_signature"),
    simulationId: text("simulation_id"),
    simulationStatus: text("simulation_status", { enum: ["passed", "failed"] }),
    simulationSlot: integer("simulation_slot"),
    simulationUnitsConsumed: integer("simulation_units_consumed"),
    simulationLogsHash: text("simulation_logs_hash"),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
  },
  (table) => [
    index("positions_user_created_idx").on(table.userEmail, table.createdAt),
    index("positions_wallet_idx").on(table.walletAddress),
    uniqueIndex("positions_quote_unique_idx").on(table.quoteId),
  ],
);

export const transactionSimulations = pgTable(
  "transaction_simulations",
  {
    id: text("id").primaryKey(),
    userEmail: text("user_email").notNull(),
    walletAddress: text("wallet_address").notNull(),
    quoteId: text("quote_id").notNull(),
    positionAddress: text("position_address").notNull(),
    transactionHash: text("transaction_hash").notNull(),
    status: text("status", { enum: ["passed", "failed"] }).notNull(),
    slot: integer("slot"),
    unitsConsumed: integer("units_consumed"),
    logsJson: text("logs_json").notNull(),
    logsHash: text("logs_hash").notNull(),
    errorJson: text("error_json"),
    transactionSignature: text("transaction_signature"),
    submissionStatus: text("submission_status", { enum: ["not_sent", "confirmed", "failed"] }).notNull(),
    submissionError: text("submission_error"),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
    confirmedAt: timestamp("confirmed_at", { mode: "date", withTimezone: true }),
  },
  (table) => [
    index("transaction_simulations_user_created_idx").on(table.userEmail, table.createdAt),
    index("transaction_simulations_quote_idx").on(table.quoteId),
    uniqueIndex("transaction_simulations_hash_unique_idx").on(table.transactionHash),
  ],
);

export const rfqQuotes = pgTable(
  "rfq_quotes",
  {
    id: text("id").primaryKey(),
    requestId: text("request_id").notNull(),
    marketAddress: text("market_address").notNull().default(""),
    oracleAddress: text("oracle_address").notNull().default(""),
    maker: text("maker").notNull(),
    symbol: text("symbol").notNull(),
    direction: text("direction", { enum: ["up", "down"] }).notNull(),
    amount: doublePrecision("amount").notNull(),
    premium: doublePrecision("premium").notNull(),
    maxPayout: doublePrecision("max_payout").notNull(),
    strike: doublePrecision("strike").notNull(),
    capPrice: doublePrecision("cap_price").notNull(),
    breakeven: doublePrecision("breakeven").notNull(),
    pricingVolatility: doublePrecision("implied_volatility").notNull(),
    volatilitySource: text("volatility_source").notNull().default("legacy"),
    effectiveLeverage: doublePrecision("effective_leverage").notNull(),
    latencyMs: integer("latency_ms").notNull(),
    badge: text("badge").notNull(),
    expiryDays: integer("expiry_days").notNull(),
    expiryCode: text("expiry_code").notNull().default("7D"),
    optionExpiryAt: timestamp("option_expiry_at", { mode: "date", withTimezone: true }).notNull().default(sql`to_timestamp(0)`),
    observationWindowSeconds: integer("observation_window_seconds").notNull().default(900),
    tradeLockSeconds: integer("trade_lock_seconds").notNull().default(300),
    payoff: integer("payoff").notNull(),
    expiresAt: timestamp("expires_at", { mode: "date", withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { mode: "date", withTimezone: true }),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
  },
  (table) => [index("rfq_quotes_expiry_idx").on(table.expiresAt)],
);

export const authNonces = pgTable(
  "auth_nonces",
  {
    nonce: text("nonce").primaryKey(),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { mode: "date", withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { mode: "date", withTimezone: true }),
  },
  (table) => [index("auth_nonces_expires_idx").on(table.expiresAt)],
);

export const launchActions = pgTable(
  "launch_actions",
  {
    id: text("id").primaryKey(),
    userKey: text("user_key").notNull(),
    walletAddress: text("wallet_address").notNull(),
    kind: text("kind", { enum: ["create_market", "create_pool", "authorize_market"] }).notNull(),
    paramsJson: text("params_json").notNull(),
    targetAddress: text("target_address").notNull(),
    secondaryAddress: text("secondary_address"),
    transactionMessageHash: text("transaction_message_hash").notNull(),
    transactionHash: text("transaction_hash"),
    simulationStatus: text("simulation_status", { enum: ["passed", "failed"] }),
    simulationSlot: integer("simulation_slot"),
    simulationUnitsConsumed: integer("simulation_units_consumed"),
    simulationLogsJson: text("simulation_logs_json"),
    simulationLogsHash: text("simulation_logs_hash"),
    simulationErrorJson: text("simulation_error_json"),
    transactionSignature: text("transaction_signature"),
    submissionStatus: text("submission_status", { enum: ["prepared", "confirmed", "failed"] }).notNull(),
    submissionError: text("submission_error"),
    postStateVerified: boolean("post_state_verified"),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
    confirmedAt: timestamp("confirmed_at", { mode: "date", withTimezone: true }),
  },
  (table) => [
    index("launch_actions_user_created_idx").on(table.userKey, table.createdAt),
    index("launch_actions_wallet_created_idx").on(table.walletAddress, table.createdAt),
    uniqueIndex("launch_actions_message_unique_idx").on(table.transactionMessageHash),
    uniqueIndex("launch_actions_transaction_hash_unique_idx").on(table.transactionHash),
    uniqueIndex("launch_actions_signature_unique_idx").on(table.transactionSignature),
  ],
);

export const closeActions = pgTable(
  "close_actions",
  {
    id: text("id").primaryKey(),
    walletAddress: text("wallet_address").notNull(),
    positionAddress: text("position_address").notNull(),
    poolAddress: text("pool_address").notNull(),
    marketAddress: text("market_address").notNull(),
    buyerDestinationAddress: text("buyer_destination_address").notNull(),
    treasuryDestinationAddress: text("treasury_destination_address").notNull(),
    buybackAmountAtoms: text("buyback_amount_atoms").notNull(),
    minProceedsAtoms: text("min_proceeds_atoms").notNull(),
    fairValueAtoms: text("fair_value_atoms").notNull(),
    spreadBps: doublePrecision("spread_bps").notNull(),
    quoteExpiry: integer("quote_expiry").notNull(),
    transactionMessageHash: text("transaction_message_hash").notNull(),
    transactionHash: text("transaction_hash"),
    simulationStatus: text("simulation_status", { enum: ["passed", "failed"] }),
    simulationSlot: integer("simulation_slot"),
    simulationUnitsConsumed: integer("simulation_units_consumed"),
    simulationLogsJson: text("simulation_logs_json"),
    simulationLogsHash: text("simulation_logs_hash"),
    simulationErrorJson: text("simulation_error_json"),
    transactionSignature: text("transaction_signature"),
    submissionStatus: text("submission_status", { enum: ["prepared", "confirmed", "failed"] }).notNull(),
    submissionError: text("submission_error"),
    preBuyerAtoms: text("pre_buyer_atoms").notNull(),
    postBuyerAtoms: text("post_buyer_atoms"),
    postStateVerified: boolean("post_state_verified"),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
    confirmedAt: timestamp("confirmed_at", { mode: "date", withTimezone: true }),
  },
  (table) => [
    index("close_actions_wallet_created_idx").on(table.walletAddress, table.createdAt),
    index("close_actions_position_idx").on(table.positionAddress),
    uniqueIndex("close_actions_message_unique_idx").on(table.transactionMessageHash),
    uniqueIndex("close_actions_transaction_hash_unique_idx").on(table.transactionHash),
    uniqueIndex("close_actions_signature_unique_idx").on(table.transactionSignature),
  ],
);

export const liquidityActions = pgTable(
  "liquidity_actions",
  {
    id: text("id").primaryKey(),
    userEmail: text("user_email").notNull(),
    walletAddress: text("wallet_address").notNull(),
    poolAddress: text("pool_address").notNull(),
    providerAddress: text("provider_address").notNull(),
    action: text("action", { enum: ["deposit", "withdraw"] }).notNull(),
    amountAtoms: text("amount_atoms").notNull(),
    minimumOutputAtoms: text("minimum_output_atoms").notNull(),
    sharesAtoms: text("shares_atoms"),
    deadline: integer("deadline").notNull(),
    transactionMessageHash: text("transaction_message_hash").notNull(),
    transactionHash: text("transaction_hash"),
    simulationStatus: text("simulation_status", { enum: ["passed", "failed"] }),
    simulationSlot: integer("simulation_slot"),
    simulationUnitsConsumed: integer("simulation_units_consumed"),
    simulationLogsJson: text("simulation_logs_json"),
    simulationLogsHash: text("simulation_logs_hash"),
    simulationErrorJson: text("simulation_error_json"),
    transactionSignature: text("transaction_signature"),
    submissionStatus: text("submission_status", { enum: ["prepared", "confirmed", "failed"] }).notNull(),
    submissionError: text("submission_error"),
    preWalletAtoms: text("pre_wallet_atoms").notNull(),
    prePoolAtoms: text("pre_pool_atoms").notNull(),
    preSharesAtoms: text("pre_shares_atoms").notNull(),
    postWalletAtoms: text("post_wallet_atoms"),
    postPoolAtoms: text("post_pool_atoms"),
    postSharesAtoms: text("post_shares_atoms"),
    createdAt: timestamp("created_at", { mode: "date", withTimezone: true }).notNull(),
    confirmedAt: timestamp("confirmed_at", { mode: "date", withTimezone: true }),
  },
  (table) => [
    index("liquidity_actions_user_created_idx").on(table.userEmail, table.createdAt),
    index("liquidity_actions_wallet_created_idx").on(table.walletAddress, table.createdAt),
    uniqueIndex("liquidity_actions_message_unique_idx").on(table.transactionMessageHash),
    uniqueIndex("liquidity_actions_transaction_hash_unique_idx").on(table.transactionHash),
    uniqueIndex("liquidity_actions_signature_unique_idx").on(table.transactionSignature),
  ],
);
