// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITendSettlementOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITendSettlementOracle";
  readonly sourceName: "contracts/interfaces/ITendSettlementOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"underlying","type":"address"},{"internalType":"uint64","name":"expiry","type":"uint64"}],"name":"settlementPrice","outputs":[{"internalType":"uint256","name":"price","type":"uint256"},{"internalType":"uint64","name":"observedAt","type":"uint64"},{"internalType":"bool","name":"finalized","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ITendSettlementOracle.sol";
  readonly buildInfoId: "solc-0_8_28-957cedf7fc534134c6d293d365781cc4d938b8bb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITendSettlementOracle"]: ITendSettlementOracle$Type;
    ["contracts/interfaces/ITendSettlementOracle.sol:ITendSettlementOracle"]: ITendSettlementOracle$Type;
  }
}