// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITendEligibility$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITendEligibility";
  readonly sourceName: "contracts/interfaces/ITendEligibility.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"address","name":"underlying","type":"address"}],"name":"canTrade","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ITendEligibility.sol";
  readonly buildInfoId: "solc-0_8_28-957cedf7fc534134c6d293d365781cc4d938b8bb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITendEligibility"]: ITendEligibility$Type;
    ["contracts/interfaces/ITendEligibility.sol:ITendEligibility"]: ITendEligibility$Type;
  }
}